using UnityEngine;

namespace MusicProgram.CrestURP
{
    /// <summary>Inspector-readable checklist embedded in the generated scene.</summary>
    public sealed class CrestURPShowcaseNotes : MonoBehaviour
    {
        [TextArea(8, 18)]
        public string controls =
            "DESKTOP: WASD move, Q/E descend/ascend, Shift sprint, hold RMB to look.\n" +
            "VR: OpenXR headset drives the Main Camera; move the XR Origin to cross the surface.\n\n" +
            "VALIDATION: start above water, lower through Y=0, inspect the meniscus, then look at the seafloor/rocks for projected caustics. " +
            "The player, floating bodies, surface submarine and fish school inject forces into Crest Dynamic Waves. " +
            "Planar reflections render above water. Caustics use Snell-refraction ray differentials and the live surface-to-receiver Jacobian, with no procedural caustic pattern. " +
            "Use CrestURPWaveController for presets, runtime time control, Dynamic Waves, foam, and detailed 14-band spectrum authoring. " +
            "Floating bodies use Crest GPU displacement queries. Ocean LOD, FFT waves and foam are generated by the MIT Crest Water 4 core.";
    }
}
